travis:
  secure:
    BINSTAR_TOKEN: XcDnG8YY+mJwKCJVrfBK6TeKT0H3GvbC9scSzYen21mvJGHP15Yg/PxaDtAeFPhEEIWBxU7qfk6umFJ6snL+NKgtLWue4syaCGyl/6i0P9vw3fzJ3C9B7JTxe/mKh/JAwFbrFHEiGf26tVnZTjKhsWOjH7h5+P0llC4CMy8cXI4NA8U4EowZPZcnc9iTfDOcfQyJdnzLr/GMvKN2W7XH1HvqPZXdad6M4y2sbBGG+SiZJWmtbzBAE4oV8p3SQ9m7rfVsKl8saSaS8kQFe6OabR2XUg5AYfWevEJgPy/yUAXQqPJYjVst+tzE4F0nUQvKdi4EIHSygYvWCWlNsntqXT8+Ovfh2piXePjUcH5+2PD+8cxrD0a2r9muTC0A+JpzNKQDpNXTf1axUwPvAJGnmkvxgfC20ZyVBvUIvSndXGiBqC6oVr8rTnBdEss516EEmNfjetx/3JWCQX9CnX2zHjePbxsKjzJobPNAXvr0AVEwocMNd7fCH+iC/6+/Tt7PZkNdpn1x/mK9DB3f98I0VC1nFP0B92TdyPh7VIrlPv4nNwkcDvaBgyNkfKFubUxf1BjQFgwS0IainpdTj3drG+PYUEGlARRYaJs8SzR7Od//zZW8muGaycly9YjM2Jnp+27b8+Crri43fO44E3S61ou6AwGgoPBLQ/W07bK3RVI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
